spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/portfolio
    #url: jdbc:postgresql://postgres:5432/dynamics
    #username: andi
    #password: andi
    username: portfolio-db-user
    password: Portfolio-db00?
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


server:
  port: 8081





